#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v13
# autospec commit: 2659038
#
# Source0 file verified with key 0x5AE420CC0209989E (ktonibud@gmail.com)
#
Name     : znc
Version  : 1.9.1
Release  : 32
URL      : https://znc.in/releases/znc-1.9.1.tar.gz
Source0  : https://znc.in/releases/znc-1.9.1.tar.gz
Source1  : https://znc.in/releases/znc-1.9.1.tar.gz.sig
Source2  : 5AE420CC0209989E.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: znc-bin = %{version}-%{release}
Requires: znc-data = %{version}-%{release}
Requires: znc-lib = %{version}-%{release}
Requires: znc-license = %{version}-%{release}
Requires: znc-locales = %{version}-%{release}
Requires: znc-man = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : gettext-dev
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : gnupg
BuildRequires : icu4c-dev
BuildRequires : openssl-dev
BuildRequires : perl
BuildRequires : pkg-config
BuildRequires : pkgconfig(icu-uc)
BuildRequires : pkgconfig(libargon2)
BuildRequires : pkgconfig(libsasl2)
BuildRequires : python3-dev
BuildRequires : qtbase-dev
BuildRequires : swig
BuildRequires : tcl-dev tk-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# [![ZNC](logo.png)](https://znc.in) - An advanced IRC bouncer
[![GitHub Workflow Status](https://img.shields.io/github/actions/workflow/status/znc/znc/build.yml?branch=master&label=linux)](https://github.com/znc/znc/actions/workflows/build.yml)
[![Jenkins Build Status](https://img.shields.io/jenkins/s/https/jenkins.znc.in/job/znc/job/znc/job/master.svg?label=freebsd)](https://jenkins.znc.in/job/znc/job/znc/job/master/)
[![AppVeyor Build status](https://img.shields.io/appveyor/ci/DarthGandalf/znc/master.svg?label=windows)](https://ci.appveyor.com/project/DarthGandalf/znc/branch/master)
[![Coverage Status](https://img.shields.io/codecov/c/github/znc/znc.svg)](https://codecov.io/gh/znc/znc)

%package bin
Summary: bin components for the znc package.
Group: Binaries
Requires: znc-data = %{version}-%{release}
Requires: znc-license = %{version}-%{release}

%description bin
bin components for the znc package.


%package data
Summary: data components for the znc package.
Group: Data

%description data
data components for the znc package.


%package dev
Summary: dev components for the znc package.
Group: Development
Requires: znc-lib = %{version}-%{release}
Requires: znc-bin = %{version}-%{release}
Requires: znc-data = %{version}-%{release}
Provides: znc-devel = %{version}-%{release}
Requires: znc = %{version}-%{release}

%description dev
dev components for the znc package.


%package lib
Summary: lib components for the znc package.
Group: Libraries
Requires: znc-data = %{version}-%{release}
Requires: znc-license = %{version}-%{release}

%description lib
lib components for the znc package.


%package license
Summary: license components for the znc package.
Group: Default

%description license
license components for the znc package.


%package locales
Summary: locales components for the znc package.
Group: Default

%description locales
locales components for the znc package.


%package man
Summary: man components for the znc package.
Group: Default

%description man
man components for the znc package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 5AE420CC0209989E' gpg.status
%setup -q -n znc-1.9.1
cd %{_builddir}/znc-1.9.1
pushd ..
cp -a znc-1.9.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720118073
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1720118073
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/znc
cp %{_builddir}/znc-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/znc/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/znc-%{version}/third_party/cctz/LICENSE.txt %{buildroot}/usr/share/package-licenses/znc/77ca6ddbb42e1c1c589a0874f0ad28b7da4cccbb || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang znc-admindebug
%find_lang znc-adminlog
%find_lang znc-alias
%find_lang znc-autoattach
%find_lang znc-autocycle
%find_lang znc-autoop
%find_lang znc-autoreply
%find_lang znc-autovoice
%find_lang znc-awaystore
%find_lang znc-block_motd
%find_lang znc-blockuser
%find_lang znc-bouncedcc
%find_lang znc-buffextras
%find_lang znc-cert
%find_lang znc-certauth
%find_lang znc-chansaver
%find_lang znc-clearbufferonmsg
%find_lang znc-clientnotify
%find_lang znc-controlpanel
%find_lang znc-corecaps
%find_lang znc-crypt
%find_lang znc-ctcpflood
%find_lang znc-cyrusauth
%find_lang znc-dcc
%find_lang znc-disconkick
%find_lang znc-fail2ban
%find_lang znc-flooddetach
%find_lang znc-identfile
%find_lang znc-imapauth
%find_lang znc-keepnick
%find_lang znc-kickrejoin
%find_lang znc-lastseen
%find_lang znc-listsockets
%find_lang znc-log
%find_lang znc-missingmotd
%find_lang znc-modperl
%find_lang znc-modpython
%find_lang znc-modules_online
%find_lang znc-nickserv
%find_lang znc-notes
%find_lang znc-notify_connect
%find_lang znc-perform
%find_lang znc-perleval
%find_lang znc-pyeval
%find_lang znc-raw
%find_lang znc-route_replies
%find_lang znc-sample
%find_lang znc-samplewebapi
%find_lang znc-sasl
%find_lang znc-savebuff
%find_lang znc-send_raw
%find_lang znc-shell
%find_lang znc-simple_away
%find_lang znc-stickychan
%find_lang znc-stripcontrols
%find_lang znc-watch
%find_lang znc-webadmin
%find_lang znc
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/znc
/usr/bin/znc
/usr/bin/znc-buildmod

%files data
%defattr(-,root,root,-)
/usr/share/znc/cmake/CMakeFindDependencyMacroPC.cmake
/usr/share/znc/cmake/ZNCConfig.cmake
/usr/share/znc/cmake/ZNCConfigVersion.cmake
/usr/share/znc/cmake/use_homebrew.cmake
/usr/share/znc/cmake/znc_internal-relwithdebinfo.cmake
/usr/share/znc/cmake/znc_internal.cmake
/usr/share/znc/cmake/znc_public.cmake
/usr/share/znc/modules/blockuser/tmpl/blockuser_WebadminUser.tmpl
/usr/share/znc/modules/cert/tmpl/index.tmpl
/usr/share/znc/modules/certauth/tmpl/index.tmpl
/usr/share/znc/modules/lastseen/tmpl/index.tmpl
/usr/share/znc/modules/lastseen/tmpl/lastseen_WebadminUser.tmpl
/usr/share/znc/modules/listsockets/tmpl/index.tmpl
/usr/share/znc/modules/notes/files/trash.gif
/usr/share/znc/modules/notes/tmpl/index.tmpl
/usr/share/znc/modules/perform/tmpl/index.tmpl
/usr/share/znc/modules/q/tmpl/index.tmpl
/usr/share/znc/modules/samplewebapi/tmpl/index.tmpl
/usr/share/znc/modules/sasl/tmpl/index.tmpl
/usr/share/znc/modules/send_raw/files/select.js
/usr/share/znc/modules/send_raw/tmpl/index.tmpl
/usr/share/znc/modules/stickychan/tmpl/index.tmpl
/usr/share/znc/modules/stickychan/tmpl/stickychan_WebadminChan.tmpl
/usr/share/znc/modules/webadmin/files/webadmin.css
/usr/share/znc/modules/webadmin/files/webadmin.js
/usr/share/znc/modules/webadmin/tmpl/add_edit_chan.tmpl
/usr/share/znc/modules/webadmin/tmpl/add_edit_network.tmpl
/usr/share/znc/modules/webadmin/tmpl/add_edit_user.tmpl
/usr/share/znc/modules/webadmin/tmpl/del_network.tmpl
/usr/share/znc/modules/webadmin/tmpl/del_user.tmpl
/usr/share/znc/modules/webadmin/tmpl/encoding_settings.tmpl
/usr/share/znc/modules/webadmin/tmpl/index.tmpl
/usr/share/znc/modules/webadmin/tmpl/listusers.tmpl
/usr/share/znc/modules/webadmin/tmpl/settings.tmpl
/usr/share/znc/modules/webadmin/tmpl/traffic.tmpl
/usr/share/znc/translations/bg-BG
/usr/share/znc/translations/de-DE
/usr/share/znc/translations/es-ES
/usr/share/znc/translations/fr-FR
/usr/share/znc/translations/id-ID
/usr/share/znc/translations/it-IT
/usr/share/znc/translations/nl-NL
/usr/share/znc/translations/pl-PL
/usr/share/znc/translations/pt-BR
/usr/share/znc/translations/pt-PT
/usr/share/znc/translations/ru-RU
/usr/share/znc/translations/tr-TR
/usr/share/znc/webskins/_default_/pub/External.png
/usr/share/znc/webskins/_default_/pub/_default_.css
/usr/share/znc/webskins/_default_/pub/favicon.ico
/usr/share/znc/webskins/_default_/pub/global.css
/usr/share/znc/webskins/_default_/pub/jquery-1.11.2.js
/usr/share/znc/webskins/_default_/pub/jquery-1.11.2.min.js
/usr/share/znc/webskins/_default_/pub/jquery-ui-sortable.1.11.4.css
/usr/share/znc/webskins/_default_/pub/jquery-ui-sortable.1.11.4.js
/usr/share/znc/webskins/_default_/pub/jquery-ui-sortable.1.11.4.min.css
/usr/share/znc/webskins/_default_/pub/jquery-ui-sortable.1.11.4.min.js
/usr/share/znc/webskins/_default_/pub/robots.txt
/usr/share/znc/webskins/_default_/pub/selectize-0.12.1.css
/usr/share/znc/webskins/_default_/pub/selectize-standalone-0.12.1.js
/usr/share/znc/webskins/_default_/pub/selectize-standalone-0.12.1.min.js
/usr/share/znc/webskins/_default_/tmpl/Banner.tmpl
/usr/share/znc/webskins/_default_/tmpl/BaseHeader.tmpl
/usr/share/znc/webskins/_default_/tmpl/BreadCrumbs.tmpl
/usr/share/znc/webskins/_default_/tmpl/DocType.tmpl
/usr/share/znc/webskins/_default_/tmpl/Error.tmpl
/usr/share/znc/webskins/_default_/tmpl/ExtraHeader.tmpl
/usr/share/znc/webskins/_default_/tmpl/Footer.tmpl
/usr/share/znc/webskins/_default_/tmpl/FooterTag.tmpl
/usr/share/znc/webskins/_default_/tmpl/Header.tmpl
/usr/share/znc/webskins/_default_/tmpl/InfoBar.tmpl
/usr/share/znc/webskins/_default_/tmpl/LoginBar.tmpl
/usr/share/znc/webskins/_default_/tmpl/LowerBanner.tmpl
/usr/share/znc/webskins/_default_/tmpl/Menu.tmpl
/usr/share/znc/webskins/_default_/tmpl/MessageBar.tmpl
/usr/share/znc/webskins/_default_/tmpl/Options.tmpl
/usr/share/znc/webskins/_default_/tmpl/_csrf_check.tmpl
/usr/share/znc/webskins/_default_/tmpl/index.tmpl
/usr/share/znc/webskins/dark-clouds/pub/clouds-header.jpg
/usr/share/znc/webskins/dark-clouds/pub/dark-clouds.css
/usr/share/znc/webskins/dark-clouds/pub/favicon.ico
/usr/share/znc/webskins/dark-clouds/tmpl/Banner.tmpl
/usr/share/znc/webskins/dark-clouds/tmpl/FooterTag.tmpl
/usr/share/znc/webskins/dark-clouds/tmpl/Header.tmpl
/usr/share/znc/webskins/dark-clouds/tmpl/LowerBanner.tmpl
/usr/share/znc/webskins/forest/pub/favicon.ico
/usr/share/znc/webskins/forest/pub/forest-header.png
/usr/share/znc/webskins/forest/pub/forest.css
/usr/share/znc/webskins/forest/tmpl/Banner.tmpl
/usr/share/znc/webskins/forest/tmpl/FooterTag.tmpl
/usr/share/znc/webskins/forest/tmpl/Header.tmpl
/usr/share/znc/webskins/forest/tmpl/LowerBanner.tmpl
/usr/share/znc/webskins/ice/pub/favicon.ico
/usr/share/znc/webskins/ice/pub/ice.css
/usr/share/znc/webskins/ice/pub/linkbg.jpg
/usr/share/znc/webskins/ice/pub/pagebg.gif
/usr/share/znc/webskins/ice/tmpl/FooterTag.tmpl
/usr/share/znc/webskins/ice/tmpl/Header.tmpl

%files dev
%defattr(-,root,root,-)
/usr/include/znc/Buffer.h
/usr/include/znc/Chan.h
/usr/include/znc/Client.h
/usr/include/znc/Config.h
/usr/include/znc/Csocket.h
/usr/include/znc/ExecSock.h
/usr/include/znc/FileUtils.h
/usr/include/znc/HTTPSock.h
/usr/include/znc/IRCNetwork.h
/usr/include/znc/IRCSock.h
/usr/include/znc/Listener.h
/usr/include/znc/MD5.h
/usr/include/znc/Message.h
/usr/include/znc/Modules.h
/usr/include/znc/Nick.h
/usr/include/znc/Query.h
/usr/include/znc/SHA256.h
/usr/include/znc/SSLVerifyHost.h
/usr/include/znc/Server.h
/usr/include/znc/Socket.h
/usr/include/znc/Template.h
/usr/include/znc/Threads.h
/usr/include/znc/Translation.h
/usr/include/znc/User.h
/usr/include/znc/Utils.h
/usr/include/znc/WebModules.h
/usr/include/znc/ZNCDebug.h
/usr/include/znc/ZNCString.h
/usr/include/znc/defines.h
/usr/include/znc/main.h
/usr/include/znc/version.h
/usr/include/znc/znc.h
/usr/include/znc/znc_export_lib_export.h
/usr/include/znc/zncconfig.h
/usr/lib64/pkgconfig/znc.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/znc/admindebug.so
/V3/usr/lib64/znc/adminlog.so
/V3/usr/lib64/znc/alias.so
/V3/usr/lib64/znc/autoattach.so
/V3/usr/lib64/znc/autocycle.so
/V3/usr/lib64/znc/autoop.so
/V3/usr/lib64/znc/autoreply.so
/V3/usr/lib64/znc/autovoice.so
/V3/usr/lib64/znc/awaynick.so
/V3/usr/lib64/znc/awaystore.so
/V3/usr/lib64/znc/block_motd.so
/V3/usr/lib64/znc/blockuser.so
/V3/usr/lib64/znc/bouncedcc.so
/V3/usr/lib64/znc/buffextras.so
/V3/usr/lib64/znc/cert.so
/V3/usr/lib64/znc/certauth.so
/V3/usr/lib64/znc/chansaver.so
/V3/usr/lib64/znc/clearbufferonmsg.so
/V3/usr/lib64/znc/clientnotify.so
/V3/usr/lib64/znc/controlpanel.so
/V3/usr/lib64/znc/corecaps.so
/V3/usr/lib64/znc/crypt.so
/V3/usr/lib64/znc/ctcpflood.so
/V3/usr/lib64/znc/cyrusauth.so
/V3/usr/lib64/znc/dcc.so
/V3/usr/lib64/znc/disconkick.so
/V3/usr/lib64/znc/fail2ban.so
/V3/usr/lib64/znc/flooddetach.so
/V3/usr/lib64/znc/identfile.so
/V3/usr/lib64/znc/imapauth.so
/V3/usr/lib64/znc/keepnick.so
/V3/usr/lib64/znc/kickrejoin.so
/V3/usr/lib64/znc/lastseen.so
/V3/usr/lib64/znc/listsockets.so
/V3/usr/lib64/znc/log.so
/V3/usr/lib64/znc/missingmotd.so
/V3/usr/lib64/znc/modules_online.so
/V3/usr/lib64/znc/nickserv.so
/V3/usr/lib64/znc/notes.so
/V3/usr/lib64/znc/notify_connect.so
/V3/usr/lib64/znc/perform.so
/V3/usr/lib64/znc/raw.so
/V3/usr/lib64/znc/route_replies.so
/V3/usr/lib64/znc/sample.so
/V3/usr/lib64/znc/samplewebapi.so
/V3/usr/lib64/znc/sasl.so
/V3/usr/lib64/znc/savebuff.so
/V3/usr/lib64/znc/schat.so
/V3/usr/lib64/znc/send_raw.so
/V3/usr/lib64/znc/shell.so
/V3/usr/lib64/znc/simple_away.so
/V3/usr/lib64/znc/stickychan.so
/V3/usr/lib64/znc/stripcontrols.so
/V3/usr/lib64/znc/watch.so
/V3/usr/lib64/znc/webadmin.so
/usr/lib64/znc/admindebug.so
/usr/lib64/znc/adminlog.so
/usr/lib64/znc/alias.so
/usr/lib64/znc/autoattach.so
/usr/lib64/znc/autocycle.so
/usr/lib64/znc/autoop.so
/usr/lib64/znc/autoreply.so
/usr/lib64/znc/autovoice.so
/usr/lib64/znc/awaynick.so
/usr/lib64/znc/awaystore.so
/usr/lib64/znc/block_motd.so
/usr/lib64/znc/blockuser.so
/usr/lib64/znc/bouncedcc.so
/usr/lib64/znc/buffextras.so
/usr/lib64/znc/cert.so
/usr/lib64/znc/certauth.so
/usr/lib64/znc/chansaver.so
/usr/lib64/znc/clearbufferonmsg.so
/usr/lib64/znc/clientnotify.so
/usr/lib64/znc/controlpanel.so
/usr/lib64/znc/corecaps.so
/usr/lib64/znc/crypt.so
/usr/lib64/znc/ctcpflood.so
/usr/lib64/znc/cyrusauth.so
/usr/lib64/znc/dcc.so
/usr/lib64/znc/disconkick.so
/usr/lib64/znc/fail2ban.so
/usr/lib64/znc/flooddetach.so
/usr/lib64/znc/identfile.so
/usr/lib64/znc/imapauth.so
/usr/lib64/znc/keepnick.so
/usr/lib64/znc/kickrejoin.so
/usr/lib64/znc/lastseen.so
/usr/lib64/znc/listsockets.so
/usr/lib64/znc/log.so
/usr/lib64/znc/missingmotd.so
/usr/lib64/znc/modules_online.so
/usr/lib64/znc/nickserv.so
/usr/lib64/znc/notes.so
/usr/lib64/znc/notify_connect.so
/usr/lib64/znc/perform.so
/usr/lib64/znc/raw.so
/usr/lib64/znc/route_replies.so
/usr/lib64/znc/sample.so
/usr/lib64/znc/samplewebapi.so
/usr/lib64/znc/sasl.so
/usr/lib64/znc/savebuff.so
/usr/lib64/znc/schat.so
/usr/lib64/znc/send_raw.so
/usr/lib64/znc/shell.so
/usr/lib64/znc/simple_away.so
/usr/lib64/znc/stickychan.so
/usr/lib64/znc/stripcontrols.so
/usr/lib64/znc/watch.so
/usr/lib64/znc/webadmin.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/znc/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/znc/77ca6ddbb42e1c1c589a0874f0ad28b7da4cccbb

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/znc-buildmod.1
/usr/share/man/man1/znc.1

%files locales -f znc-admindebug.lang -f znc-adminlog.lang -f znc-alias.lang -f znc-autoattach.lang -f znc-autocycle.lang -f znc-autoop.lang -f znc-autoreply.lang -f znc-autovoice.lang -f znc-awaystore.lang -f znc-block_motd.lang -f znc-blockuser.lang -f znc-bouncedcc.lang -f znc-buffextras.lang -f znc-cert.lang -f znc-certauth.lang -f znc-chansaver.lang -f znc-clearbufferonmsg.lang -f znc-clientnotify.lang -f znc-controlpanel.lang -f znc-corecaps.lang -f znc-crypt.lang -f znc-ctcpflood.lang -f znc-cyrusauth.lang -f znc-dcc.lang -f znc-disconkick.lang -f znc-fail2ban.lang -f znc-flooddetach.lang -f znc-identfile.lang -f znc-imapauth.lang -f znc-keepnick.lang -f znc-kickrejoin.lang -f znc-lastseen.lang -f znc-listsockets.lang -f znc-log.lang -f znc-missingmotd.lang -f znc-modperl.lang -f znc-modpython.lang -f znc-modules_online.lang -f znc-nickserv.lang -f znc-notes.lang -f znc-notify_connect.lang -f znc-perform.lang -f znc-perleval.lang -f znc-pyeval.lang -f znc-raw.lang -f znc-route_replies.lang -f znc-sample.lang -f znc-samplewebapi.lang -f znc-sasl.lang -f znc-savebuff.lang -f znc-send_raw.lang -f znc-shell.lang -f znc-simple_away.lang -f znc-stickychan.lang -f znc-stripcontrols.lang -f znc-watch.lang -f znc-webadmin.lang -f znc.lang
%defattr(-,root,root,-)

