#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
# Source0 file verified with key 0x5AE420CC0209989E (ktonibud@gmail.com)
#
Name     : znc
Version  : 1.8.2
Release  : 29
URL      : https://znc.in/releases/znc-1.8.2.tar.gz
Source0  : https://znc.in/releases/znc-1.8.2.tar.gz
Source1  : https://znc.in/releases/znc-1.8.2.tar.gz.sig
Summary  : An advanced IRC proxy
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0 MIT
Requires: znc-bin = %{version}-%{release}
Requires: znc-data = %{version}-%{release}
Requires: znc-lib = %{version}-%{release}
Requires: znc-license = %{version}-%{release}
Requires: znc-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : buildreq-kde
BuildRequires : grep
BuildRequires : icu4c-dev
BuildRequires : pkgconfig(openssl)
BuildRequires : sed
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: manpages.patch

%description
# [![ZNC](https://wiki.znc.in/resources/assets/wiki.png)](https://znc.in) - An advanced IRC bouncer

%package bin
Summary: bin components for the znc package.
Group: Binaries
Requires: znc-data = %{version}-%{release}
Requires: znc-license = %{version}-%{release}

%description bin
bin components for the znc package.


%package data
Summary: data components for the znc package.
Group: Data

%description data
data components for the znc package.


%package dev
Summary: dev components for the znc package.
Group: Development
Requires: znc-lib = %{version}-%{release}
Requires: znc-bin = %{version}-%{release}
Requires: znc-data = %{version}-%{release}
Provides: znc-devel = %{version}-%{release}
Requires: znc = %{version}-%{release}

%description dev
dev components for the znc package.


%package lib
Summary: lib components for the znc package.
Group: Libraries
Requires: znc-data = %{version}-%{release}
Requires: znc-license = %{version}-%{release}

%description lib
lib components for the znc package.


%package license
Summary: license components for the znc package.
Group: Default

%description license
license components for the znc package.


%package man
Summary: man components for the znc package.
Group: Default

%description man
man components for the znc package.


%prep
%setup -q -n znc-1.8.2
cd %{_builddir}/znc-1.8.2
%patch1 -p1
pushd ..
cp -a znc-1.8.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1685476360
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make  %{?_smp_mflags}
popd
%install
export SOURCE_DATE_EPOCH=1685476360
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/znc
cp %{_builddir}/znc-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/znc/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/znc-%{version}/NOTICE %{buildroot}/usr/share/package-licenses/znc/a218ac130c95452b77527bc86fc9a4f98098f0dd || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/znc
/usr/bin/znc
/usr/bin/znc-buildmod

%files data
%defattr(-,root,root,-)
/usr/share/znc/modules/blockuser/tmpl/blockuser_WebadminUser.tmpl
/usr/share/znc/modules/cert/tmpl/index.tmpl
/usr/share/znc/modules/certauth/tmpl/index.tmpl
/usr/share/znc/modules/lastseen/tmpl/index.tmpl
/usr/share/znc/modules/lastseen/tmpl/lastseen_WebadminUser.tmpl
/usr/share/znc/modules/listsockets/tmpl/index.tmpl
/usr/share/znc/modules/notes/files/trash.gif
/usr/share/znc/modules/notes/tmpl/index.tmpl
/usr/share/znc/modules/perform/tmpl/index.tmpl
/usr/share/znc/modules/q/tmpl/index.tmpl
/usr/share/znc/modules/samplewebapi/tmpl/index.tmpl
/usr/share/znc/modules/sasl/tmpl/index.tmpl
/usr/share/znc/modules/send_raw/files/select.js
/usr/share/znc/modules/send_raw/tmpl/index.tmpl
/usr/share/znc/modules/stickychan/tmpl/index.tmpl
/usr/share/znc/modules/stickychan/tmpl/stickychan_WebadminChan.tmpl
/usr/share/znc/modules/webadmin/files/webadmin.css
/usr/share/znc/modules/webadmin/files/webadmin.js
/usr/share/znc/modules/webadmin/tmpl/add_edit_chan.tmpl
/usr/share/znc/modules/webadmin/tmpl/add_edit_network.tmpl
/usr/share/znc/modules/webadmin/tmpl/add_edit_user.tmpl
/usr/share/znc/modules/webadmin/tmpl/del_network.tmpl
/usr/share/znc/modules/webadmin/tmpl/del_user.tmpl
/usr/share/znc/modules/webadmin/tmpl/encoding_settings.tmpl
/usr/share/znc/modules/webadmin/tmpl/index.tmpl
/usr/share/znc/modules/webadmin/tmpl/listusers.tmpl
/usr/share/znc/modules/webadmin/tmpl/settings.tmpl
/usr/share/znc/modules/webadmin/tmpl/traffic.tmpl
/usr/share/znc/webskins/_default_/pub/External.png
/usr/share/znc/webskins/_default_/pub/_default_.css
/usr/share/znc/webskins/_default_/pub/favicon.ico
/usr/share/znc/webskins/_default_/pub/global.css
/usr/share/znc/webskins/_default_/pub/jquery-1.11.2.js
/usr/share/znc/webskins/_default_/pub/jquery-1.11.2.min.js
/usr/share/znc/webskins/_default_/pub/jquery-ui-sortable.1.11.4.css
/usr/share/znc/webskins/_default_/pub/jquery-ui-sortable.1.11.4.js
/usr/share/znc/webskins/_default_/pub/jquery-ui-sortable.1.11.4.min.css
/usr/share/znc/webskins/_default_/pub/jquery-ui-sortable.1.11.4.min.js
/usr/share/znc/webskins/_default_/pub/robots.txt
/usr/share/znc/webskins/_default_/pub/selectize-0.12.1.css
/usr/share/znc/webskins/_default_/pub/selectize-standalone-0.12.1.js
/usr/share/znc/webskins/_default_/pub/selectize-standalone-0.12.1.min.js
/usr/share/znc/webskins/_default_/tmpl/Banner.tmpl
/usr/share/znc/webskins/_default_/tmpl/BaseHeader.tmpl
/usr/share/znc/webskins/_default_/tmpl/BreadCrumbs.tmpl
/usr/share/znc/webskins/_default_/tmpl/DocType.tmpl
/usr/share/znc/webskins/_default_/tmpl/Error.tmpl
/usr/share/znc/webskins/_default_/tmpl/ExtraHeader.tmpl
/usr/share/znc/webskins/_default_/tmpl/Footer.tmpl
/usr/share/znc/webskins/_default_/tmpl/FooterTag.tmpl
/usr/share/znc/webskins/_default_/tmpl/Header.tmpl
/usr/share/znc/webskins/_default_/tmpl/InfoBar.tmpl
/usr/share/znc/webskins/_default_/tmpl/LoginBar.tmpl
/usr/share/znc/webskins/_default_/tmpl/LowerBanner.tmpl
/usr/share/znc/webskins/_default_/tmpl/Menu.tmpl
/usr/share/znc/webskins/_default_/tmpl/MessageBar.tmpl
/usr/share/znc/webskins/_default_/tmpl/Options.tmpl
/usr/share/znc/webskins/_default_/tmpl/_csrf_check.tmpl
/usr/share/znc/webskins/_default_/tmpl/index.tmpl
/usr/share/znc/webskins/dark-clouds/pub/clouds-header.jpg
/usr/share/znc/webskins/dark-clouds/pub/dark-clouds.css
/usr/share/znc/webskins/dark-clouds/pub/favicon.ico
/usr/share/znc/webskins/dark-clouds/tmpl/Banner.tmpl
/usr/share/znc/webskins/dark-clouds/tmpl/FooterTag.tmpl
/usr/share/znc/webskins/dark-clouds/tmpl/Header.tmpl
/usr/share/znc/webskins/dark-clouds/tmpl/LowerBanner.tmpl
/usr/share/znc/webskins/forest/pub/favicon.ico
/usr/share/znc/webskins/forest/pub/forest-header.png
/usr/share/znc/webskins/forest/pub/forest.css
/usr/share/znc/webskins/forest/tmpl/Banner.tmpl
/usr/share/znc/webskins/forest/tmpl/FooterTag.tmpl
/usr/share/znc/webskins/forest/tmpl/Header.tmpl
/usr/share/znc/webskins/forest/tmpl/LowerBanner.tmpl
/usr/share/znc/webskins/ice/pub/favicon.ico
/usr/share/znc/webskins/ice/pub/ice.css
/usr/share/znc/webskins/ice/pub/linkbg.jpg
/usr/share/znc/webskins/ice/pub/pagebg.gif
/usr/share/znc/webskins/ice/tmpl/FooterTag.tmpl
/usr/share/znc/webskins/ice/tmpl/Header.tmpl

%files dev
%defattr(-,root,root,-)
/usr/include/znc/Buffer.h
/usr/include/znc/Chan.h
/usr/include/znc/Client.h
/usr/include/znc/Config.h
/usr/include/znc/Csocket.h
/usr/include/znc/ExecSock.h
/usr/include/znc/FileUtils.h
/usr/include/znc/HTTPSock.h
/usr/include/znc/IRCNetwork.h
/usr/include/znc/IRCSock.h
/usr/include/znc/Listener.h
/usr/include/znc/MD5.h
/usr/include/znc/Message.h
/usr/include/znc/Modules.h
/usr/include/znc/Nick.h
/usr/include/znc/Query.h
/usr/include/znc/SHA256.h
/usr/include/znc/SSLVerifyHost.h
/usr/include/znc/Server.h
/usr/include/znc/Socket.h
/usr/include/znc/Template.h
/usr/include/znc/Threads.h
/usr/include/znc/Translation.h
/usr/include/znc/User.h
/usr/include/znc/Utils.h
/usr/include/znc/WebModules.h
/usr/include/znc/ZNCDebug.h
/usr/include/znc/ZNCString.h
/usr/include/znc/defines.h
/usr/include/znc/main.h
/usr/include/znc/version.h
/usr/include/znc/znc.h
/usr/include/znc/zncconfig.h
/usr/lib64/pkgconfig/znc.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/znc/admindebug.so
/V3/usr/lib64/znc/adminlog.so
/V3/usr/lib64/znc/alias.so
/V3/usr/lib64/znc/autoattach.so
/V3/usr/lib64/znc/autocycle.so
/V3/usr/lib64/znc/autoop.so
/V3/usr/lib64/znc/autoreply.so
/V3/usr/lib64/znc/autovoice.so
/V3/usr/lib64/znc/awaynick.so
/V3/usr/lib64/znc/awaystore.so
/V3/usr/lib64/znc/block_motd.so
/V3/usr/lib64/znc/blockuser.so
/V3/usr/lib64/znc/bouncedcc.so
/V3/usr/lib64/znc/buffextras.so
/V3/usr/lib64/znc/cert.so
/V3/usr/lib64/znc/certauth.so
/V3/usr/lib64/znc/chansaver.so
/V3/usr/lib64/znc/clearbufferonmsg.so
/V3/usr/lib64/znc/clientnotify.so
/V3/usr/lib64/znc/controlpanel.so
/V3/usr/lib64/znc/crypt.so
/V3/usr/lib64/znc/ctcpflood.so
/V3/usr/lib64/znc/dcc.so
/V3/usr/lib64/znc/disconkick.so
/V3/usr/lib64/znc/fail2ban.so
/V3/usr/lib64/znc/flooddetach.so
/V3/usr/lib64/znc/identfile.so
/V3/usr/lib64/znc/imapauth.so
/V3/usr/lib64/znc/keepnick.so
/V3/usr/lib64/znc/kickrejoin.so
/V3/usr/lib64/znc/lastseen.so
/V3/usr/lib64/znc/listsockets.so
/V3/usr/lib64/znc/log.so
/V3/usr/lib64/znc/missingmotd.so
/V3/usr/lib64/znc/modules_online.so
/V3/usr/lib64/znc/nickserv.so
/V3/usr/lib64/znc/notes.so
/V3/usr/lib64/znc/notify_connect.so
/V3/usr/lib64/znc/perform.so
/V3/usr/lib64/znc/raw.so
/V3/usr/lib64/znc/route_replies.so
/V3/usr/lib64/znc/sample.so
/V3/usr/lib64/znc/samplewebapi.so
/V3/usr/lib64/znc/sasl.so
/V3/usr/lib64/znc/savebuff.so
/V3/usr/lib64/znc/schat.so
/V3/usr/lib64/znc/send_raw.so
/V3/usr/lib64/znc/shell.so
/V3/usr/lib64/znc/simple_away.so
/V3/usr/lib64/znc/stickychan.so
/V3/usr/lib64/znc/stripcontrols.so
/V3/usr/lib64/znc/watch.so
/V3/usr/lib64/znc/webadmin.so
/usr/lib64/znc/admindebug.so
/usr/lib64/znc/adminlog.so
/usr/lib64/znc/alias.so
/usr/lib64/znc/autoattach.so
/usr/lib64/znc/autocycle.so
/usr/lib64/znc/autoop.so
/usr/lib64/znc/autoreply.so
/usr/lib64/znc/autovoice.so
/usr/lib64/znc/awaynick.so
/usr/lib64/znc/awaystore.so
/usr/lib64/znc/block_motd.so
/usr/lib64/znc/blockuser.so
/usr/lib64/znc/bouncedcc.so
/usr/lib64/znc/buffextras.so
/usr/lib64/znc/cert.so
/usr/lib64/znc/certauth.so
/usr/lib64/znc/chansaver.so
/usr/lib64/znc/clearbufferonmsg.so
/usr/lib64/znc/clientnotify.so
/usr/lib64/znc/controlpanel.so
/usr/lib64/znc/crypt.so
/usr/lib64/znc/ctcpflood.so
/usr/lib64/znc/dcc.so
/usr/lib64/znc/disconkick.so
/usr/lib64/znc/fail2ban.so
/usr/lib64/znc/flooddetach.so
/usr/lib64/znc/identfile.so
/usr/lib64/znc/imapauth.so
/usr/lib64/znc/keepnick.so
/usr/lib64/znc/kickrejoin.so
/usr/lib64/znc/lastseen.so
/usr/lib64/znc/listsockets.so
/usr/lib64/znc/log.so
/usr/lib64/znc/missingmotd.so
/usr/lib64/znc/modules_online.so
/usr/lib64/znc/nickserv.so
/usr/lib64/znc/notes.so
/usr/lib64/znc/notify_connect.so
/usr/lib64/znc/perform.so
/usr/lib64/znc/raw.so
/usr/lib64/znc/route_replies.so
/usr/lib64/znc/sample.so
/usr/lib64/znc/samplewebapi.so
/usr/lib64/znc/sasl.so
/usr/lib64/znc/savebuff.so
/usr/lib64/znc/schat.so
/usr/lib64/znc/send_raw.so
/usr/lib64/znc/shell.so
/usr/lib64/znc/simple_away.so
/usr/lib64/znc/stickychan.so
/usr/lib64/znc/stripcontrols.so
/usr/lib64/znc/watch.so
/usr/lib64/znc/webadmin.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/znc/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/znc/a218ac130c95452b77527bc86fc9a4f98098f0dd

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/znc-buildmod.1
/usr/share/man/man1/znc.1
